http:
  middlewares:
    middlewares-websocket:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          Connection: "Upgrade"
          Upgrade: "websocket"
